#!/bin/sh

SEMAGROW_SHORT_NAME="${distribution.all.package.shortname}";

echo "PREREMOVE WITH $@"

#rm -f /etc/init.d/$SEMAGROW_SHORT_NAME

set -e
case "$1" in
    remove)
	    echo "Remove";
    ;;
    upgrade)
	    echo "Upgrade";
    ;;
    fail-upgrade)
	    echo "Fail upgrade";
    ;;
esac
